services:
  announceman:
    image: announceman
    restart: unless-stopped
    build: .
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      TARGET_CHANNEL_NAME: ${TARGET_CHANNEL_NAME}
    volumes:
      - ./announceman_data:/src/announceman_data
